#!/bin/sh
# Run each test and compare
# against known good output

if [ ! -f ../comp_arm ]
then echo "Need to build ../comp_arm first!"; exit 1
fi

for i in input*
do if [ ! -f "out.$i" ]
   then echo "Can't run test on $i, no output file!"
   else
     echo -n $i
     ../comp_arm $i
     arm-linux-gnueabi-gcc -o out out.s ../lib/printint.c -static
     ./out > trial.$i
     cmp -s "out.$i" "trial.$i"
     if [ "$?" -eq "1" ]
     then echo ": failed"
       diff -c "out.$i" "trial.$i"
       echo
     else echo ": OK"
     fi
     rm -f out out.s "trial.$i"
   fi
done
